### ISSUE TITLE
Erro `AttributeError: 'int' object has no attribute 'strip'`

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/new-dataset-template#8]
Erro ocorrido durante teste de publicação [deste conjunto](https://github.com/Andrelamor/iepha-teste-template), [neste action](https://github.com/Andrelamor/iepha-teste-template/actions/runs/5557081554/jobs/10150412950):

```
Run task csv
Traceback (most recent call last):
  File "/home/runner/work/iepha-teste-template/iepha-teste-template/scripts/convert_csv.py", line 36, in <module>
    convert_csv()
  File "/home/runner/work/iepha-teste-template/iepha-teste-template/scripts/convert_csv.py", line 22, in convert_csv
    read_file[column] = [read_file[column][i].strip() for i in range(0, len(read_file))]
  File "/home/runner/work/iepha-teste-template/iepha-teste-template/scripts/convert_csv.py", line 22, in <listcomp>
    read_file[column] = [read_file[column][i].strip() for i in range(0, len(read_file))]
AttributeError: 'int' object has no attribute 'strip'
Error: Process completed with exit code 1.
```

Identifiquei que o script criado para conversão do arquivo excel para csv conferia somente se a primeira célula da coluna era string (`read_file.iloc[0][column]` ao fixar o zero) e não célula a célula.

https://github.com/transparencia-mg/new-dataset-template/blob/c458af4bda1163e4d3a8c178fc6cbbccbef57a5b/scripts/convert_csv.py#L21

**Comment by gabrielbdornas** [comment]
Tentei resolver o problema com [List Comprehension](https://www.w3schools.com/python/python_lists_comprehension.asp#:~:text=ADVERTISEMENT-,The%20Syntax,-newlist%20%3D%20%5Bexpression) (`read_file[column] = [read_file[column][i].strip() for i in range(0, len(read_file)) if isinstance(read_file[column][i], str)]`) mas não foi possível.

**Comment by gabrielbdornas** [comment]
> Tentei resolver o problema com [List Comprehension](https://www.w3schools.com/python/python_lists_comprehension.asp#:~:text=ADVERTISEMENT-,The%20Syntax,-newlist%20%3D%20%5Bexpression) (`read_file[column] = [read_file[column][i].strip() for i in range(0, len(read_file)) if isinstance(read_file[column][i], str)]`) mas não foi possível.

Utilizando um `for loop` a conversão funcionou, mas quebrou linhas quando alguma célula tinha uma nova linha incluída manualmente. [Este post](https://stackoverflow.com/a/65603853/11755155) solucionou o problema, tendo sido utilizado:

```
read_file = read_file \
                    .replace('\n', ' ', regex=True) \
                    .replace('\r', '', regex=True)
```

**Comment by gabrielbdornas** [comment]
@Andrelamor, após a correção deste issue fiz o teste de publicação [neste repositório](https://github.com/transparencia-mg/iepha-teste-template). O processo de publicação aconteceu [sem nenhum erro](https://github.com/transparencia-mg/iepha-teste-template/actions/runs/5558156928/jobs/10152889851) aparentemente.

Devido aos erros para gerar os relatórios de validação listados nos issues #1, #4  e #5 rodei a validação localmente e a mesma atestou que o arquivo está [válido](https://github.com/transparencia-mg/iepha-teste-template/blob/e66b53b996a2e94b4411856d438a3e3b911b66da/datapackage_validation.json). 

Arquivei o repositório após os testes, mas acredito que o mesmo poderá ser consultado para análise caso seja necessário.
